# Generated by Django 3.0.5 on 2020-05-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimData',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField(blank=True, db_column='CUST_ID', null=True)),
                ('poly_no', models.IntegerField(blank=True, db_column='POLY_NO', null=True)),
                ('acci_dvsn', models.IntegerField(blank=True, db_column='ACCI_DVSN', null=True)),
                ('dmnd_resn_code', models.IntegerField(blank=True, db_column='DMND_RESN_CODE', null=True)),
                ('vlid_hosp_otda', models.IntegerField(blank=True, db_column='VLID_HOSP_OTDA', null=True)),
                ('hosp_code', models.FloatField(blank=True, db_column='HOSP_CODE', null=True)),
                ('chme_lice_no', models.FloatField(blank=True, db_column='CHME_LICE_NO', null=True)),
                ('heed_hosp_yn', models.CharField(blank=True, db_column='HEED_HOSP_YN', max_length=1, null=True)),
            ],
            options={
                'db_table': 'claim_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustData',
            fields=[
                ('cust_id', models.IntegerField(db_column='CUST_ID', primary_key=True, serialize=False)),
                ('divided_set', models.IntegerField(db_column='DIVIDED_SET')),
                ('siu_cust_yn', models.CharField(db_column='SIU_CUST_YN', max_length=1, null=True)),
                ('sex', models.IntegerField(db_column='SEX')),
                ('age', models.IntegerField(db_column='AGE')),
                ('resi_cost', models.IntegerField(db_column='RESI_COST')),
                ('resi_type_code', models.FloatField(db_column='RESI_TYPE_CODE')),
                ('ctpr', models.CharField(db_column='CTPR', max_length=20)),
                ('occp_grp_1', models.CharField(db_column='OCCP_GRP_1', max_length=50)),
                ('totalprem', models.FloatField(db_column='TOTALPREM')),
                ('wedd_yn', models.CharField(db_column='WEDD_YN', max_length=1)),
                ('mate_occp_grp_1', models.CharField(blank=True, db_column='MATE_OCCP_GRP_1', max_length=30)),
                ('chld_cnt', models.FloatField(blank=True, db_column='CHLD_CNT')),
                ('ltbn_chld_age', models.IntegerField(blank=True, db_column='LTBN_CHLD_AGE')),
                ('max_prm', models.FloatField(blank=True, db_column='MAX_PRM')),
                ('cust_incm', models.FloatField(blank=True, db_column='CUST_INCM')),
                ('rcbase_hshd_incm', models.IntegerField(blank=True, db_column='RCBASE_HSHD_INCM')),
                ('jpbase_hshd_incm', models.FloatField(blank=True, db_column='JPBASE_HSHD_INCM')),
            ],
            options={
                'db_table': 'cust_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
    ]
